import '../styles/about.css';
import '../styles/button.css';
import '../styles/partners.css';
import '../styles/content.css';
import '../styles/services.css';
import '../styles/headers.css';
import '../styles/copyright.css';
import '../styles/Navbar.css';
import '../styles/testimonial.css';